positions/urls.py
from django.urls import path
from . import views

app_name = 'positions'

urlpatterns = [
    path('', views.position_list_view_home, name="home"),
    path('positions/search/', views.positionListViewSearch.as_view(), name="search"),
    path('positions/category/<int:category_id>/', views.positionListViewCategory.as_view(), name="category"),
    path('positions/institution/<int:institution_id>/', views.positionListViewInstitution.as_view(), name="institution"), 
    path('positions/<int:pk>/', views.positionDetail.as_view(), name="position"),
    # path('position/<int:position_id>/candidatar/', views.candidatar_position, name='candidatar_position'),
]

profiles/urls.py
from django.urls import path
from . import views
from .views import data_filters

app_name = 'profiles'

urlpatterns = [
    path('register/', views.register_choice_view, name='register_choice'),
    path('register/institution/', views.institution_register_view, name='institution_register'),
    path('register/voluntier/', views.voluntier_register_view, name='voluntier_register'),

    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),

    path('dashboard/', views.dashboard, name='dashboard'),

    path('match/', views.match_view, name='match'),

    # path('ajax/filter-states/', data_filters.FilterStates.as_view(), name='filter_states'),
    # path('ajax/filter-cities/', data_filters.FilterCities.as_view(), name='filter_cities'),
    # path('ajax/filter-subcategories/', data_filters.FilterSubcategories.as_view(), name='filter_subcategories'),

    path('dashboard/payment/', views.payment_view, name='payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/failure/', views.payment_failure, name='payment_failure'),
    path('payment/pending/', views.payment_pending, name='payment_pending'),

    path('dashboard/position/new/', views.Dashboardposition.as_view(), name='dashboard_position_new'),
    path('dashboard/position/delete/', views.DashboardpositionDelete.as_view(), name='dashboard_position_delete'),
    path('dashboard/position/<int:id>/edit/', views.Dashboardposition.as_view(), name='dashboard_position_edit'),
    path('dashboard/position/<int:id>/applications/', views.DashboardPositionApplications.as_view(), name='dashboard_position_applications'),
]

project/urls.py
from django.conf             import settings
from django.conf.urls.static import static
from django.contrib          import admin
from django.urls             import include, path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('positions.urls')),
    path('profiles/', include('profiles.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

positions/models.py
from django.contrib.auth.models import User
from django.conf                import settings
from django.db                  import models
from django.urls                import reverse
from django.utils.text          import slugify
from django.utils.translation   import gettext_lazy as _

from profiles.models import Institution, Voluntier


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    name     = models.CharField(max_length=65)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subcategories')

    def __str__(self):
        return self.name


class Position(models.Model):
    SHIFT_CHOICES = [
        ('morning', _('Morning')),
        ('afternoon', _('Afternoon')),
        ('night', _('Night')),
    ]


    title        = models.CharField(max_length=65, verbose_name=_('Title'))
    description  = models.CharField(max_length=165, verbose_name=_('Description'))
    slug         = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Created_at'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('Updated_at'))

    cover = models.ImageField(
        upload_to='positions/covers/%Y/%m/%d/', 
        blank=True, 
        default='', 
        verbose_name=_('Cover')
    )
    
    category = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        default=None, 
        verbose_name=_('Category')
    )

    subcategory = models.ForeignKey(
        Subcategory, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        default=None, 
        verbose_name=_('Subcategory')
    )

    profile = models.ForeignKey(Institution, on_delete=models.CASCADE)

    shift        = models.CharField(max_length=10, choices=SHIFT_CHOICES, default='morning', verbose_name=_('Shift'))
    cep          = models.CharField(max_length=100, verbose_name=_('cep'))
    state        = models.CharField(max_length=100, verbose_name=_('State'))
    city         = models.CharField(max_length=100, verbose_name=_('City'))
    neighborhood = models.CharField(max_length=100, verbose_name=_('Neighborhood'), default='')
    street       = models.CharField(max_length=255, verbose_name=_('Street'), default='')
    more         = models.CharField(max_length=255, verbose_name=_('More'), default='')


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('positions:position', args=(self.id,))

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.title)}'
            self.slug = slug

        return super().save(*args, **kwargs)


class Application(models.Model):
    position  = models.ForeignKey('position', on_delete=models.CASCADE, related_name='applications_vaga', verbose_name=_('position'))
    voluntier = models.ForeignKey(Voluntier, on_delete=models.CASCADE)

    cv   = models.FileField(upload_to='cvs/%Y/%m/%d/')
    date = models.DateTimeField(auto_now_add=True, verbose_name=_('Date'))

    def __str__(self):
        return f'{self.voluntier.email} - {self.position.title}'

    class Meta:
        verbose_name        = _('position')
        verbose_name_plural = _('positions')

positions/forms.py
from django  import forms
from .models import Application

class ApplicationForm(forms.ModelForm):
    class Meta:
        model  = Application
        fields = ['cv']

profiles/forms/position_form.py
from django                   import forms
from django.core.exceptions   import ValidationError
from .django_forms            import add_attr
from django.utils.translation import gettext_lazy as _

from collections      import defaultdict
from positions.models import Position, Subcategory


class ProfilepositionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_errors = defaultdict(list)

        add_attr(self.fields.get('category'), 'id', 'id_category')
        add_attr(self.fields.get('subcategory'), 'id', 'id_subcategory')


    class Meta:
        model = Position

        fields = [
            'title', 'description', 'category', 'subcategory', 'shift',
            'cep', 'state', 'city', 'neighborhood', 'street', 'more'
        ]

        widgets = {
            'shift': forms.Select(choices=Position.SHIFT_CHOICES),
        }

    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        cd          = self.cleaned_data

        title       = cd.get('title')
        description = cd.get('description')

        if title == description:
            self._my_errors['title'].append('O Título NÃO pode ser igual à Descrição')
            self._my_errors['description'].append('A Descrição NÃO pode ser igual ao Título')

        if self._my_errors:
            raise ValidationError(self._my_errors)

        return super_clean

    def clean_title(self):
        title = self.cleaned_data.get('title')

        if len(title) < 5:
            self._my_errors['title'].append('Deve ter pelo menos 5 caracteres')

        return title

positions/views.py
from django.db.models import Q
from django.http.response import Http404
from django.views.generic import DetailView, ListView
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.utils import translation
from django.utils.translation import gettext as _
from django.contrib import messages
from django.utils.decorators import method_decorator
from positions.models import Position, Application
from profiles.models import User, Institution, Voluntier
from .pagination import make_pagination

PER_PAGE = 6

class positionListViewBase(ListView):
    model = Position
    context_object_name = 'positions'
    ordering = ['-id']
    template_name = 'positions/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get('positions'),
            PER_PAGE
        )

        html_language = translation.get_language()

        ctx.update({
            'positions': page_obj,
            'pagination_range': pagination_range,
            'html_language': html_language,
        })
        return ctx

def position_list_view_home(request):
    user = request.user
    positions = Position.objects.all()

    institution = None
    voluntier = None

    if user.is_authenticated and not user.is_superuser:
        try:
            institution = Institution.objects.get(user=user)
        except Institution.DoesNotExist:
            institution = None

        try:
            voluntier = Voluntier.objects.get(user=user)
        except Voluntier.DoesNotExist:
            voluntier = None

    return render(
        request,
        'positions/pages/home.html',
        context={
            'user': user,
            'institution': institution,
            'voluntier': voluntier,
            'positions': positions,
        }
    )

class positionListViewCategory(positionListViewBase):
    template_name = 'positions/pages/category.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        category_translation = _('Category')

        ctx.update({
            'title': f'{ctx.get("positions")[0].category.name} - {category_translation} | '
        })

        return ctx

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            category__id=self.kwargs.get('category_id')
        )

        if not qs:
            raise Http404()

        return qs

class positionListViewSearch(positionListViewBase):
    template_name = 'positions/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get('q', '')

        if not search_term:
            raise Http404()

        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            Q(
                Q(title__icontains=search_term) |
                Q(description__icontains=search_term),
            )
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '')

        ctx.update({
            'page_title': f'Search for "{search_term}" |',
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}',
        })

        return ctx

@method_decorator(login_required, name='dispatch')
class positionDetail(DetailView):
    model = Position
    context_object_name = 'position'
    template_name = 'positions/pages/position-view.html'

    def post(self, request, *args, **kwargs):
        # Get the position object
        self.object = self.get_object()
        
        # Check if the user is a Voluntier
        try:
            voluntier = request.user.voluntier
        except Voluntier.DoesNotExist:
            voluntier = None

        if voluntier:
            # Create an Application object
            Application.objects.create(
                position=self.object,
                voluntier=voluntier
            )
            messages.success(request, _('Your application has been submitted successfully'))
            return redirect('profiles:dashboard')  # Redirect to the dashboard or another appropriate page

        messages.error(request, 'You need to be a Voluntier to apply.')
        return redirect('positions:position', pk=self.object.pk)

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        user_profile = None
        if self.request.user.is_authenticated:
            try:
                user_profile = self.request.user.voluntier
            except Voluntier.DoesNotExist:
                user_profile = None

        ctx.update({
            'is_detail_page': True,
            'user_profile': user_profile
        })

        return ctx
    
class positionListViewInstitution(positionListViewBase):
    template_name = 'positions/pages/institution.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        institution_translation = _('Institution')
        
        # Get the institution name for the title
        institution = get_object_or_404(Institution, id=self.kwargs.get('institution_id'))
        
        ctx.update({
            'title': f'{institution.name} - {institution_translation} | '
        })

        return ctx

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            profile__id=self.kwargs.get('institution_id')
        )

        if not qs:
            raise Http404()

        return qs

positions/templates/positions/partials/position.html
{% load i18n %}

<div class="position position-list-item">
    {% if position.cover %} 
        <div class="position-cover">
            <a href="{{ position.get_absolute_url }}">
                <img src="{{ position.cover.url }}" alt="Temporário">
            </a>
        </div>
    {% endif %}

    <div class="position-title-container">
        <h2 class="position-title">
            <a href="{{ position.get_absolute_url }}">
                {{ position.title }} <br>
            </a>
        </h2>
        <h4 class="position-title">
            <a href="{{ position.get_absolute_url }}">
                {{ position.category }}
            </a>
        </h4>
    </div>

    <div class="position-profile">
        {% if position.profile is not None %}
            <span class="position-profile-item">
                <i class="fas fa-user"></i>
                {% if position.profile.first_name %}
                    {{ position.profile.first_name }} {{ position.profile.last_name }}
                {% else %}
                    {{ position.profile.email }}
                {% endif %}
            </span>
        {% endif %}
    
        <span class="position-profile-item">
            <i class="fas fa-building"></i>
            <a href="{% url 'positions:institution' position.profile.id %}">
                {{ position.profile.name }}
            </a>
        </span>
    
        <span class="position-profile-item">
            <i class="fas fa-calendar-alt"></i>
            {{ position.created_at|date:"d/m/Y" }} {{ position.created_at|date:"H:i" }}
        </span>

        {% if position.category is not None %}
            {% if user.is_authenticated %}
                <span class="position-profile-item">
                    <a href="{% url 'positions:category' position.category.id %}">
                        <i class="fas fa-layer-group"></i>
                        <span> {{ position.category }} </span>
                    </a>
                </span>
            {% else %}
                <span class="position-profile-item">
                    <!-- <a href="{% url 'positions:category' position.category.id %}"> -->
                    <i class="fas fa-layer-group"></i>
                    <span> {{ position.category }} </span>
                </span>
            {% endif %}
        {% endif %}
    </div>

    <div class="position-content">
        <p>{{ position.description }}</p>
    </div>

    <div class="position-meta-container">
        <div class="position-meta position-preparation">
            <h3 class="position-meta-title">{% translate "Shift" %}: {{ position.get_shift_display }}</h3>
            <h3 class="position-meta-title">{% translate "State" %}: {{ position.state }}</h3>
            <h3 class="position-meta-title">{% translate "City" %}: {{ position.city }}</h3>
            <h3 class="position-meta-title">{% translate "Neighborhood" %}: {{ position.neighborhood }}</h3>
            <h3 class="position-meta-title">{% translate "Address" %}: {{ position.street }}, {{ position.more }} </h3>
        </div>
    </div>

    {% if is_detail_page is not True %}
        <footer class="position-footer">
            {% if user.is_authenticated %}
                <a class="position-read-more button button-dark button-full-width" href="{% url 'positions:position' position.id %}">
                    <i class="fas fa-eye"></i>
                    <span>{% translate "See more" %}...</span>
                </a>
            {% else %}
                <a class="position-read-more button button-dark button-full-width" href="{% url 'profiles:register_choice' %}">
                    <i class="fas fa-user-plus"></i>
                    <span>{% translate "Register to view more" %}</span>
                </a>
            {% endif %}
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        {% if user.is_authenticated %}
            {% if user_profile %}
                <div>
                    <p>{% translate "Name" %}: {{ user_profile.first_name }} {{ user_profile.last_name }}</p>
                    <p>{% translate "About" %}: {{ user_profile.about }}</p>
                    <p>{% translate "LinkedIn" %}: <a href="{{ user_profile.linkedin }}">{{ user_profile.linkedin }}</a></p>
                </div>

                {% if application_success %}

                    <p> {% translate "Your application has been submitted successfully" %} </p>

                {% else %}
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="styled-button">{% translate 'Apply' %}</button>
                    </form>
                {% endif %}
            {% else %}
                <p>{% translate "You need to be a Voluntier to apply" %}.</p>
            {% endif %}
        {% else %}
            <p>{% translate "You need to be logged in to apply" %}.</p>
        {% endif %}
    {% endif %}
</div>