profiles/urls.py
from django.urls import path
from . import views
from .views import data_filters

app_name = 'profiles'

urlpatterns = [
    path('register/', views.register_choice_view, name='register_choice'),
    path('register/institution/', views.institution_register_view, name='institution_register'),
    path('register/voluntier/', views.voluntier_register_view, name='voluntier_register'),

    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),

    path('dashboard/', views.dashboard, name='dashboard'),

    path('match/', views.match_view, name='match'),

    # path('ajax/filter-states/', data_filters.FilterStates.as_view(), name='filter_states'),
    # path('ajax/filter-cities/', data_filters.FilterCities.as_view(), name='filter_cities'),
    # path('ajax/filter-subcategories/', data_filters.FilterSubcategories.as_view(), name='filter_subcategories'),

    path('dashboard/payment/', views.payment_view, name='payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/failure/', views.payment_failure, name='payment_failure'),
    path('payment/pending/', views.payment_pending, name='payment_pending'),

    path('dashboard/position/new/', views.Dashboardposition.as_view(), name='dashboard_position_new'),
    path('dashboard/position/delete/', views.DashboardpositionDelete.as_view(), name='dashboard_position_delete'),
    path('dashboard/position/<int:id>/edit/', views.Dashboardposition.as_view(), name='dashboard_position_edit'),
    path('dashboard/position/<int:id>/applications/', views.DashboardPositionApplications.as_view(), name='dashboard_position_applications'),
]

project/urls.py
from django.conf             import settings
from django.conf.urls.static import static
from django.contrib          import admin
from django.urls             import include, path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('positions.urls')),
    path('profiles/', include('profiles.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profiles/models.py
from django.utils.translation   import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db                  import models

from .validators import validate_cpf, validate_cnpj


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    date_joined = models.DateTimeField(auto_now_add=True)
    email = models.EmailField('email adress', unique=True)

    is_active    = models.BooleanField(default=True)
    is_staff     = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    
    username = None
    
    REQUIRED_FIELDS = []
    USERNAME_FIELD = "email"

    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        return self.is_superuser

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        return self.is_superuser


class Institution(models.Model):
    user         = models.OneToOneField(User, on_delete=models.CASCADE)
    name         = models.CharField(max_length=255, verbose_name=_('Name'))
    cnpj         = models.CharField(max_length=18, validators=[validate_cnpj], unique=True)
    cep          = models.CharField(max_length=100, verbose_name=_('cep'))
    state        = models.CharField(max_length=100, verbose_name=_('State'), default='')
    city         = models.CharField(max_length=100, verbose_name=_('City'), default='')
    neighborhood = models.CharField(max_length=100, verbose_name=_('Neighborhood'), default='')
    street       = models.CharField(max_length=255, verbose_name=_('Street'), default='')
    more         = models.CharField(max_length=255, verbose_name=_('More'), default='')
    is_premium   = models.BooleanField(default=False, verbose_name=_('Premium'))

    def __str__(self):
        return self.name


class Voluntier(models.Model):
    user       = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, verbose_name=_('First Name'))
    last_name  = models.CharField(max_length=30, verbose_name=_('Last Name'))
    birth_date = models.DateField(verbose_name=_('Birth date'))
    cpf        = models.CharField(max_length=14, validators=[validate_cpf], unique=True)
    about      = models.CharField(max_length=2500, verbose_name=_('About'), default='')
    linkedin   = models.CharField(max_length=100, default='')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

profiles/forms/login.py
from django        import forms
from .django_forms import add_placeholder


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['email'], 'Digite seu email')
        add_placeholder(self.fields['password'], 'Digite sua senha')

    email      = forms.EmailField()
    password   = forms.CharField(
        widget = forms.PasswordInput()
    )

profiles/views/all.py
from django.contrib                 import messages
from django.contrib.auth            import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http                    import Http404
from django.shortcuts               import redirect, render, get_object_or_404
from django.urls                    import reverse
from django.utils.translation       import gettext as _
from django import forms
from profiles.forms.match_form import MatchForm
from profiles.forms            import LoginForm, InstitutionForm, VoluntierForm
from profiles.models           import User, Institution, Voluntier
from positions.models          import Position, Application
from profiles.payments import create_payment_preference



class Update_Voluntier_Form(forms.ModelForm):
    class Meta:
        model = Voluntier
        fields = ['about', 'linkedin']  

def register_choice_view(request):
    return render(request, 'profiles/pages/register_choice.html')


def institution_register_view(request):
    if request.method == 'POST':
        form = InstitutionForm(request.POST)

        if form.is_valid():
            user = User.objects.create_user(email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            Institution.objects.create(user=user, name=form.cleaned_data['name'], cnpj=form.cleaned_data['cnpj'],
                                       cep=form.cleaned_data['cep'], state=form.cleaned_data['state'], 
                                       city=form.cleaned_data['city'], neighborhood=form.cleaned_data['neighborhood'],
                                       street=form.cleaned_data['street'], more=form.cleaned_data['more'],)
            messages.success(request, _('Your Institution has been created, please log in.'))
            return redirect(reverse('profiles:login'))
    else:
        form = InstitutionForm()
    return render(request, 'profiles/pages/institution_register.html', {'form': form})


def voluntier_register_view(request):
    if request.method == 'POST':
        form = VoluntierForm(request.POST)

        if form.is_valid():
            user = User.objects.create_user(email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            Voluntier.objects.create(user=user, first_name=form.cleaned_data['first_name'], last_name=form.cleaned_data['last_name'], 
                                     birth_date=form.cleaned_data['birth_date'], cpf=form.cleaned_data['cpf'])
            messages.success(request, _('Your Voluntier account has been created, please log in.'))
            return redirect(reverse('profiles:login'))
    else:
        form = VoluntierForm()
    return render(request, 'profiles/pages/voluntier_register.html', {'form': form})


def login_view(request):
    form = LoginForm()
    return render(request, 'profiles/pages/login.html', {
        'form': form,
        'form_action': reverse('profiles:login_create')
    })


def match_view(request):
    form = MatchForm(request.GET or None)
    positions = Position.objects.all()

    if form.is_valid():
        if form.cleaned_data['shift']:
            positions = positions.filter(shift=form.cleaned_data['shift'])

        if form.cleaned_data['state']:
            positions = positions.filter(state__iexact=form.cleaned_data['state'])

        if form.cleaned_data['city']:
            positions = positions.filter(city__iexact=form.cleaned_data['city'])

        if form.cleaned_data['neighborhood']:
            positions = positions.filter(neighborhood__iexact=form.cleaned_data['neighborhood'])

        if form.cleaned_data['category']:
            positions = positions.filter(category=form.cleaned_data['category'])

    return render(request, 'positions/pages/match.html', {
        'positions': positions,
        'form': form,
    })


def login_create(request):
    if not request.POST:
        raise Http404()

    form = LoginForm(request.POST)

    if form.is_valid():
        email   = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')

        # Atualize a autenticação para usar o email como username
        user = authenticate(request, username=email, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, _("You're logged in!"))
            return redirect(reverse('profiles:dashboard'))
        else:
            messages.error(request, _('Invalid credentials'))
    else:
        messages.error(request, _('Invalid email or password'))

    return redirect(reverse('profiles:login'))


@login_required(login_url='profiles:login', redirect_field_name='next')
def logout_view(request):
    if request.method != 'POST':
        messages.error(request, _('Invalid logout request'))
        return redirect(reverse('profiles:login'))

    logout(request)
    messages.success(request, _('Logout Done Successfully'))
    return redirect(reverse('profiles:login'))


@login_required(login_url='profiles:login', redirect_field_name='next')
def dashboard(request):
    user = request.user
    match_form = MatchForm(request.GET or None)
    voluntier_form = None  # Initialize as None

    user_type = None
    profile = None

    if not request.user.is_superuser:
        try:
            institution = Institution.objects.get(user=user)
            user_type = 'ONG'
            profile = institution
        except Institution.DoesNotExist:
            institution = None

        try:
            voluntier = Voluntier.objects.get(user=user)
            user_type = 'Voluntier'
            profile = voluntier
            # Initialize the VoluntierForm with existing data
            voluntier_form = Update_Voluntier_Form(request.POST or None, instance=voluntier)

            if request.method == 'POST' and voluntier_form.is_valid():
                voluntier_form.save()
                messages.success(request, _('Voluntier data saved successfully'))
                return redirect('profiles:dashboard')

        except Voluntier.DoesNotExist:
            voluntier = None

        if user_type == 'Voluntier':
            applications = Application.objects.filter(voluntier=profile)
            return render(
                request,
                'profiles/pages/dashboard.html',
                context={
                    'applications': applications,
                    'user_type': user_type,
                    'user': user,
                    'profile': profile,
                    'form': match_form,
                    'voluntier_form': voluntier_form,  # Add the VoluntierForm to the context
                }
            )

        elif user_type == 'ONG':
            positions = Position.objects.filter(profile=institution)
            return render(
                request,
                'profiles/pages/dashboard.html',
                context={
                    'positions': positions,
                    'user_type': user_type,
                    'user': user,
                    'profile': profile,
                    'form': match_form,
                }
            )
    else:
        # Logic for superuser if needed
        pass

    return render(request, 'profiles/pages/dashboard.html', {'form': match_form})


def payment_view(request):
    preference_id = create_payment_preference()
    
    mercado_pago_url = f"https://www.mercadopago.com.br/checkout/v1/redirect?pref_id={preference_id}"
    return redirect(mercado_pago_url)


@login_required
def payment_success(request):
    try:
        institution = request.user.institution
        institution.is_premium = True
        institution.save()
        messages.success(request, _('Your payment was successful, and your account is now premium!'))
    except Institution.DoesNotExist:
        messages.error(request, _('Institution not found.'))
    return redirect('profiles:dashboard')

@login_required
def payment_failure(request):
    messages.error(request, _('There was an issue with your payment. Please try again.'))
    return redirect('profiles:dashboard')

@login_required
def payment_pending(request):
    messages.info(request, _('Your payment is pending. We will notify you once it is complete.'))
    return redirect('profiles:dashboard')

profiles/views/dashboard.py
# profiles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts               import render, get_object_or_404

from positions.models import position, Application
from profiles.models  import User, Institution, Voluntier


@login_required
def dashboard(request):
    profile = request.user.profile

    # Inicializa o contexto com o perfil e o tipo de usuário
    context = {
        'profile': profile,
        'user_type': profile.user_type,
    }

    # Identifica o tipo de usuário e busca os dados correspondentes
    if profile.user_type == 'Voluntier':
        applications = Application.objects.filter(voluntier=request.user)
        context['applications'] = applications
        
    else:
        positions = position.objects.filter(profile=request.user)
        context['positions'] = positions

    return render(request, 'profiles/pages/dashboard.html', context)

profiles/views/dashboard_vaga.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http.response import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from profiles.forms.vaga_form import ProfileVagaForm
from vagas.models import Vaga


@method_decorator(
    login_required(login_url='profiles:login', redirect_field_name='next'),
    name='dispatch'
)
class DashboardVaga(View):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def setup(self, *args, **kwargs):
        return super().setup(*args, **kwargs)

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_vaga(self, id=None):
        vaga = None

        if id is not None:
            vaga = Vaga.objects.filter(
                profile=self.request.user,
                pk=id,
            ).first()

            if not vaga:
                raise Http404()

        return vaga

    def render_vaga(self, form):
        return render(
            self.request,
            'profiles/pages/dashboard_vaga.html',
            context={
                'form': form
            }
        )

    def get(self, request, id=None):
        vaga = self.get_vaga(id)
        form = ProfileVagaForm(instance=vaga)
        return self.render_vaga(form)

    def post(self, request, id=None):
        vaga = self.get_vaga(id)
        form = ProfileVagaForm(
            data=request.POST or None,
            files=request.FILES or None,
            instance=vaga
        )

        if form.is_valid():
            # Agora, o form é válido e eu posso tentar salvar
            vaga = form.save(commit=False)

            vaga.profile = request.user
            vaga.requirements_is_html = False

            vaga.save()

            messages.success(request, 'Sua vaga foi salva com sucesso!')
            return redirect(
                reverse(
                    'profiles:dashboard_vaga_edit', args=(
                        vaga.id,
                    )
                )
            )

        return self.render_vaga(form)


@method_decorator(
    login_required(login_url='profiles:login', redirect_field_name='next'),
    name='dispatch'
)
class DashboardVagaDelete(DashboardVaga):
    def post(self, *args, **kwargs):
        vaga = self.get_vaga(self.request.POST.get('id'))
        vaga.delete()
        messages.success(self.request, 'Deleted successfully.')
        return redirect(reverse('profiles:dashboard'))

profiles/templates/profiles/pages/dashboard.html
<!-- profiles/templates/profiles/pages/dashboard.html -->
{% extends 'global/base.html' %}

{% load i18n %}

{% block title %}Dashboard ({{ profile }}) | {% endblock title %}

{% block content %}
  <div class="main-content center container">
    <h2>Dashboard </h2>
    <h3> ({{ profile }}) </h3>

    {% include 'profiles/partials/login_message.html' %}
    {% include 'global/partials/messages.html' %}

    <div class="profiles-dashboard-container">
      {% if user_type == 'Voluntier' %}

      <h2> {% translate 'Voluntier Profile' %} </h2> <br>
      
      <form method="post" action="">
        {% csrf_token %}
        {{ voluntier_form.as_p }}
        <button type="submit" class="styled-button"> {% translate 'Save' %}</button> 
      </form>

      <h3>{% translate 'Find Matching positions' %}</h3>

      <form method="get" action="{% url 'profiles:match' %}">
        {% csrf_token %}

          <div id="centered-form" class="form-group">
              <label for="shift">{% translate 'Shift' %}</label>
              <select name="shift" id="shift">
                  {% for value, display in form.fields.shift.choices %}
                      <option value="{{ value }}" {% if form.data.shift == value %}selected{% endif %}>{{ display }}</option>
                  {% endfor %}
              </select>
          </div>

          <div id="centered-form" class="form-group">
              <label for="category">{% translate 'Category' %}</label>
              <select name="category" id="category">
                  {% for category in form.fields.category.queryset %}
                      <option value="{{ category.id }}" {% if form.data.category == category.id|stringformat:"s" %}selected{% endif %}>{{ category.name }}</option>
                  {% endfor %}
              </select>
          </div>

          <div id="centered-form" class="form-group">
              <label for="state">{% translate 'State' %}</label>
              <select name="state" id="state">
                  {% for value, display in form.fields.state.choices %}
                      <option value="{{ value }}" {% if form.data.state == value %}selected{% endif %}>{{ display }}</option>
                  {% endfor %}
              </select>
          </div>

          <div id="centered-form" class="form-group">
              <label for="city">{% translate 'City' %}</label>
              <select name="city" id="city">
                  {% for value, display in form.fields.city.choices %}
                      <option value="{{ value }}" {% if form.data.city == value %}selected{% endif %}>{{ display }}</option>
                  {% endfor %}
              </select>
          </div>

          <div id="centered-form" class="form-group">
              <label for="neighborhood">{% translate 'Neighborhood' %}</label>
              <select name="neighborhood" id="neighborhood">
                  {% for value, display in form.fields.neighborhood.choices %}
                      <option value="{{ value }}" {% if form.data.neighborhood == value %}selected{% endif %}>{{ display }}</option>
                  {% endfor %}
              </select>
          </div>

          <button type="submit" class="styled-button">{% translate 'Match' %}</button>
      </form>

      {% endif %}

      {% if user_type == 'ONG' %}

      <h2> {% translate 'Institution Profile' %} </h2> <br>

      <a href="{% url 'profiles:payment' %}" class="styled-button"> {% translate 'Pay for Premium' %}</a> <br> <br>

      <a href="{% url 'profiles:dashboard_position_new' %}" id="create-new-position">➕ {% translate 'Create a new position' %}</a>
      <h3>{% translate 'positions' %}</h3> 

      <ul>
        {% for position in positions %}
          <li>
            {{ position.title }}
            <br>
            <a href="{% url 'profiles:dashboard_position_edit' position.id %}" class="plaintext-button">⚙️ {% translate 'Edit' %}</a> <b>|</b>
            <a href="{% url 'profiles:dashboard_position_applications' position.id %}" class="plaintext-button">📝 {% translate 'Applications' %}</a> <b>|</b>
            <form class="inline-form form-delete" action="{% url 'profiles:dashboard_position_delete' %}" method='POST'>
              {% csrf_token %}
              <input type="hidden" name="id" value="{{ position.id }}">
              <button class="plaintext-button" type="submit">❌ {% translate 'Delete' %}</button>
            </form>
          </li>
          <br>
        {% empty %}
          <li>
            <p>{% translate 'You do not have any position' %}.</p>
          </li>
        {% endfor %}
      </ul>

      {% elif user_type == 'Voluntier' %}
      <h3>{% translate 'Applications' %}</h3>                                            
      <ul>
        {% for application in applications %}
          <li>
            {{ application.position.title }} - {% translate 'application made at' %} {{ application.date }}
          </li>
        {% empty %}
          <li>
            <p>{% translate 'You have not applied for any position' %}.</p>                                            
          </li>
        {% endfor %}
      </ul>

      {% else %}
      <p>{% translate 'User type not recognized' %}.</p>
      {% endif %}
    </div>
  </div>
  
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const forms = document.querySelectorAll('.form-delete');
      forms.forEach(form => {
        form.addEventListener('submit', function(e) {
          e.preventDefault();
          const confirmed = confirm('Tem certeza que deseja excluir esta vaga?')
          if (confirmed) {
            this.submit();
          }
        });
      });
    });
  </script>
  
{% endblock content %}

profiles/templates/profiles/pages/dashboard_position.html
{% extends 'global/base.html' %}

{% load i18n %}
{% load static %}

{% block title %} Create position | {% endblock title %}

{% block content %}

  <div class="main-content center container">
    <h2>{% translate 'Create position' %}</h2>
    
    {% include 'global/partials/messages.html' %}
    <form id="grid-form" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}

      <button id="btn-lil-far" type="submit" class="styled-button">{% translate 'Save' %}</button>
    </form>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
        const cepInput = document.getElementById('id_cep');
        
        function debounce(func, wait) {
            let timeout;
            return function(...args) {
                clearTimeout(timeout);
                timeout = setTimeout(() => func.apply(this, args), wait);
            };
        }

        function fetchAddress(cep) {
            if (cep.length === 8) {
                fetch(`https://viacep.com.br/ws/${cep}/json/`)
                    .then(response => response.json())
                    .then(data => {
                        if (!data.erro) {
                            document.getElementById('id_state').value = data.uf;
                            document.getElementById('id_city').value = data.localidade;
                            document.getElementById('id_neighborhood').value = data.bairro;
                            document.getElementById('id_street').value = data.logradouro;
                        } else {
                            alert('CEP não encontrado.');
                        }
                    })
                    .catch(error => console.error('Error fetching CEP:', error));
            }
        }

        if (cepInput) {
            cepInput.addEventListener('input', debounce(function() {
                const cep = this.value.replace(/\D/g, '');
                fetchAddress(cep);
            }, 500));
        }
    });
  </script>

{% endblock content %}

profiles/templates/profiles/pages/dashboard_vaga.html
{% extends 'global/base.html' %}

{% block title %}Dashboard Vaga | {% endblock title %}

{% block content %}
  <div class="main-content center container">
    <h2>Dashboard Vaga</h2>
    {% include 'global/partials/messages.html' %}
    {% include 'profiles/partials/login_message.html' %}

    <div class="left">
      {% include 'global/partials/form.html' %}
    </div>
  </div>
{% endblock content %}

profiles/templates/profiles/pages/institution_register.html
{% extends 'global/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Register Institution' %} | {% endblock title %}

{% block content %}
  <div class="main-content center container">
    <h2>{% trans 'Register Institution' %}</h2>
  </div>

  {% include 'global/partials/messages.html' %}
  {% include 'global/partials/form.html' with form_action=request.path %}

  <script>
    document.addEventListener('DOMContentLoaded', function() {
        const cepInput = document.getElementById('id_cep');
        
        // Debounce function to delay the execution
        function debounce(func, wait) {
            let timeout;
            return function(...args) {
                clearTimeout(timeout);
                timeout = setTimeout(() => func.apply(this, args), wait);
            };
        }
    
        // Function to fetch and populate address fields
        function fetchAddress(cep) {
            if (cep.length === 8) {
                fetch(`https://viacep.com.br/ws/${cep}/json/`)
                    .then(response => response.json())
                    .then(data => {
                        if (!data.erro) {
                            document.getElementById('id_state').value = data.uf;
                            document.getElementById('id_city').value = data.localidade;
                            document.getElementById('id_neighborhood').value = data.bairro;
                            document.getElementById('id_street').value = data.logradouro;
                        } else {
                            alert('CEP não encontrado.');
                        }
                    })
                    .catch(error => console.error('Error fetching CEP:', error));
            }
        }
    
        // Attach the debounced function to the input event
        if (cepInput) {
            cepInput.addEventListener('input', debounce(function() {
                const cep = this.value.replace(/\D/g, '');
                fetchAddress(cep);
            }, 500)); // Adjust the delay as needed (500ms is a common choice)
        }
    });
    </script>

{% endblock content %}

profiles/templates/profiles/pages/login.html
{% extends 'global/base.html' %}

{% block title %}Login | {% endblock title %}

{% block content %}
  <div class="main-content center container">
    <h2>Login</h2>
    {% include 'profiles/partials/login_message.html' %}
  </div>

  {% include 'global/partials/messages.html' %}

  {% if not user.is_authenticated %}
    <form method="POST" action="{% url 'profiles:login_create' %}">
      {% csrf_token %}
      
      <div class="form-group">
        <label for="id_email">Email</label>
        <input type="email" name="email" required id="id_email" placeholder="Digite seu email">
      </div>

      <div class="form-group">
        <label for="id_password">Senha</label>
        <input type="password" name="password" required id="id_password" placeholder="Digite sua senha">
      </div>

      <button id="btn-far" type="submit" class="styled-button">Login</button>
    </form>

  {% endif %}

{% endblock content %}

profiles/templates/profiles/pages/position_applications.html
{% extends 'global/base.html' %}

{% load i18n %}

{% block title %}{% translate "Applications for" %} {{ position.title }}{% endblock title %}

{% block content %}
<div id="id-div-applications">
    <h2>{% translate "Applications for" %} {{ position.title }}</h2>

    <ul id="application-item">
        {% for application in applications %}
            <li>
                <b>{% translate "Name" %}:</b> {{ application.voluntier.first_name }} {{ application.voluntier.last_name }} <b>| Email:</b> <span id="span-email">{{ application.voluntier.user.email }}</span> <b>| LinkedIn:</b> <a href="{{ application.voluntier.linkedin }}" id="a-linkedin" target="_blank">{{ application.voluntier.linkedin }}</a>
                <br><br><b>{% translate "About" %}:</b> {{ application.voluntier.about }}
            </li>
            <br>
        {% empty %}
            <li>{% translate "No applications found." %}</li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

profiles/templates/profiles/pages/register_choice.html
{% extends 'global/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Register' %} | {% endblock title %}

{% block content %}

  <div class="main-content center container">
    <h2>{% trans 'Register' %}</h2>
    <a href="{% url 'profiles:institution_register' %}">{% trans 'Register as Institution' %}</a>
    <a href="{% url 'profiles:voluntier_register' %}">{% trans 'Register as Voluntier' %}</a>
  </div>

{% endblock content %}

profiles/templates/profiles/pages/register_view.html
{% extends 'global/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Register' %} | {% endblock title %}

{% block content %}
  <div class="main-content center container">
    <h2>{% trans 'Register' %}</h2>
  </div>

  {% include 'global/partials/messages.html' %}
  {% include 'global/partials/form.html' %} 
  
{% endblock content %}

profiles/templates/profiles/pages/voluntier_register.html
{% extends 'global/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Register Voluntier' %} | {% endblock title %}

{% block content %}

  <div class="main-content center container">
    <h2>{% trans 'Register Voluntier' %}</h2>
  </div>

  {% include 'global/partials/messages.html' %}
  {% include 'global/partials/form.html' %} 
  
{% endblock content %}